import { useState, useRef, useEffect, useMemo } from 'react';
import {
  View, Text, StyleSheet, ScrollView, TouchableOpacity,
  SafeAreaView, StatusBar, Image, Dimensions, Animated, Easing,
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { getFoodImage } from '../../src/services/imageSearch';
import { router } from 'expo-router';
import type { Palette } from '../../src/constants/colors';
import { useColors } from '../../src/state/theme';

function shimColors(c: Palette) {
  return {
    bg: c.bg, card: c.bgCard, cardAlt: c.bgElevated, border: c.border,
    primary: c.primary, gold: c.gold, textPrimary: c.textPrimary,
    textSecondary: c.textSecondary, textMuted: c.textMuted,
    green: c.scoreGood, red: c.scorePoor, blue: c.hydration, teal: '#2DD4BF',
  };
}

const TABS = ['Skin Nutrients', 'Top Foods', 'Anti-Inflammatory', 'Avoid', 'Dietary Fats'];

function buildSkinNutrients(Colors: ReturnType<typeof shimColors>) {
  return [
  {
    nutrient: 'Vitamin A (Retinol)',
    role: 'Essential for epidermal cell differentiation and turnover. Deficiency causes hyperkeratosis (thick, scaly skin). Regulates sebaceous gland function. Stimulates collagen gene expression.',
    sources: 'Liver (highest bioavailable source), grass-fed butter and animal fats, egg yolks, whole dairy. Beta-carotene from plant foods converts poorly to retinol in many people.',
    skinBenefit: 'Anti-aging, anti-acne, normalises skin turnover',
    deficiencySign: 'Dry, rough, scaly skin; follicular hyperkeratosis (KP-like); reduced night vision',
    icon: '🥩',
    color: Colors.primary,
  },
  {
    nutrient: 'Vitamin C (Ascorbic Acid)',
    role: 'Essential cofactor for collagen synthesis (prolyl and lysyl hydroxylase). Cannot make stable collagen without adequate vitamin C. Potent antioxidant that neutralises UV-induced free radicals. Regenerates vitamin E.',
    sources: 'Bell peppers (highest), citrus fruits, kiwi, broccoli, strawberries, guava, blackcurrants. Unlike vitamin A, not concentrated in animal foods.',
    skinBenefit: 'Collagen synthesis, brightening, antioxidant defence',
    deficiencySign: 'Slow wound healing, easy bruising (poor collagen), bleeding gums, rough skin',
    icon: '🍊',
    color: Colors.gold,
  },
  {
    nutrient: 'Vitamin E (Tocopherol)',
    role: 'Primary lipid-phase antioxidant. Protects lipid membranes (including stratum corneum barrier lipids) from oxidation. Regenerated by vitamin C. Concentrated in skin — actively transported there.',
    sources: 'Sunflower seeds, almonds, hazelnuts, grass-fed animal fats, olive oil, avocado',
    skinBenefit: 'Barrier protection, antioxidant, wound healing',
    deficiencySign: 'Increased skin fragility, impaired wound healing, peripheral neuropathy',
    icon: '🌻',
    color: Colors.green,
  },
  {
    nutrient: 'Vitamin D',
    role: 'Regulates epidermal differentiation and proliferation. Modulates skin immune function — critically important for inflammatory skin conditions (eczema, psoriasis, rosacea). Skin can synthesise from UVB exposure.',
    sources: 'Fatty fish (salmon, mackerel, sardines), grass-fed butter and animal fats, egg yolks, fortified foods. Supplementation often needed at northern latitudes.',
    skinBenefit: 'Immune modulation, barrier function, anti-inflammatory',
    deficiencySign: 'Increased skin infections, impaired barrier, worsened eczema/psoriasis',
    icon: '☀️',
    color: Colors.gold,
  },
  {
    nutrient: 'Zinc',
    role: '300+ enzymes require zinc. In skin: essential for wound healing, sebaceous gland regulation, anti-inflammatory activity, and collagen synthesis. Low zinc is strongly associated with acne and impaired wound healing.',
    sources: 'Oysters (highest by far), beef, lamb, pumpkin seeds, hemp seeds, chickpeas (lower bioavailability from plant sources)',
    skinBenefit: 'Acne, wound healing, sebum control, collagen',
    deficiencySign: 'Slow wound healing, acne, eczema, hair loss, impaired taste/smell',
    icon: '🦪',
    color: Colors.blue,
  },
  {
    nutrient: 'Omega-3 Fatty Acids (EPA, DHA)',
    role: 'Incorporated into cell membranes, improving fluidity and barrier function. Strongly anti-inflammatory — EPA inhibits the arachidonic acid inflammatory pathway. Reduces prostaglandin E2 which drives acne and inflammatory skin conditions.',
    sources: 'Fatty fish (salmon, mackerel, sardines, herring), fish oil supplements, grass-fed beef (higher omega-3 than grain-fed), walnuts (ALA — less efficient conversion)',
    skinBenefit: 'Anti-inflammatory, barrier, acne, eczema, dry skin',
    deficiencySign: 'Dry, flaky skin, increased inflammatory skin conditions, rough skin',
    icon: '🐟',
    color: Colors.teal,
  },
  {
    nutrient: 'Collagen (Dietary)',
    role: 'Dietary collagen is broken down to amino acids and dipeptides. Hydroxyproline-containing peptides from collagen are absorbed intact and may signal fibroblasts to increase collagen synthesis. Clinical trials show modest but measurable improvement in skin elasticity and hydration.',
    sources: 'Bone broth, gelatin, collagen powder supplements, skin-on poultry, fish (especially skin and scales, which are rich in type I collagen)',
    skinBenefit: 'Skin elasticity, hydration, fine line reduction',
    deficiencySign: 'Not a classic deficiency disease — but low collagen diet associated with accelerated skin laxity',
    icon: '🍖',
    color: Colors.primary,
  },
  {
    nutrient: 'Silicon (Silica)',
    role: 'Essential for collagen cross-linking and glycosaminoglycan synthesis. Silicon is found in high concentrations in the dermis and is required for skin, hair, and nail structural integrity. Often overlooked in nutrition discussions.',
    sources: 'Horsetail tea (highest), oats, barley, whole grains, cucumber, bell peppers, beer (from hops and malted barley)',
    skinBenefit: 'Collagen integrity, skin firmness, nail strength',
    deficiencySign: 'Brittle nails, thinning hair, loss of skin firmness',
    icon: '🌾',
    color: Colors.teal,
  },
  ];
}

const TOP_FOODS = [
  { food: 'Wild-caught fatty fish', why: 'Omega-3 EPA/DHA (anti-inflammatory), zinc, vitamin D, astaxanthin (antioxidant 6000× more potent than vitamin C). Salmon 3× weekly measurably reduces inflammatory skin markers in studies.', emoji: '🐟', rating: 5 },
  { food: 'Grass-fed beef liver', why: 'The most nutrient-dense food on earth. Retinol (most bioavailable vitamin A), B12, zinc, copper, iron, CoQ10. One serving (75g) provides weeks\'s worth of skin-supporting retinol, zinc, and copper.', emoji: '🥩', rating: 5 },
  { food: 'Oysters', why: 'Highest zinc food source by far (74mg per 100g vs beef\'s 8mg). Zinc is critical for wound healing, sebaceous gland regulation, and acne. Also high in copper (cofactor for lysyl oxidase — collagen cross-linking enzyme).', emoji: '🦪', rating: 5 },
  { food: 'Bone broth', why: 'Gelatin and collagen peptides, glycine (anti-inflammatory amino acid, essential for collagen synthesis), proline and hydroxyproline (collagen structural amino acids). Clinical trials show collagen peptide supplementation improves skin elasticity.', emoji: '🍖', rating: 4 },
  { food: 'Bell peppers (red/yellow)', why: 'Highest vitamin C content of any commonly eaten food — more than citrus. Red bell pepper: 180mg vitamin C per 100g (citrus: 50mg). Also contains carotenoids (beta-carotene, lutein) that accumulate in skin and provide antioxidant protection.', emoji: '🫑', rating: 4 },
  { food: 'Egg yolks', why: 'Biotin (supports fatty acid synthesis for barrier lipids), vitamins A, D, E, K2 (all fat-soluble skin vitamins), choline (membrane phospholipid precursor), and lutein/zeaxanthin (carotenoid antioxidants). The most nutrient-dense part of the egg is the yolk.', emoji: '🥚', rating: 4 },
  { food: 'Walnuts', why: 'Highest plant omega-3 (ALA — converts inefficiently but contributes). Also rich in vitamin E, zinc, polyphenols (ellagic acid), and selenium. Studies show walnut consumption reduces biomarkers of inflammation in skin.', emoji: '🌰', rating: 4 },
  { food: 'Avocado', why: 'Monounsaturated fatty acids (oleic acid — the same fat that dominates human sebum) for barrier support, vitamin E, vitamin C, carotenoids, and glutathione. Also contains beta-sitosterol, which has anti-inflammatory properties relevant to eczema and psoriasis.', emoji: '🥑', rating: 4 },
  { food: 'Fermented foods', why: 'Gut microbiome directly affects skin (gut-skin axis). Fermented foods (kefir, yoghurt, kimchi, sauerkraut, kombucha) support microbiome diversity, reduce intestinal permeability ("leaky gut"), and lower systemic inflammation — all of which measurably improve inflammatory skin conditions.', emoji: '🥛', rating: 4 },
  { food: 'Dark chocolate (80%+)', why: 'Flavanols improve blood flow to skin, increase skin hydration and density. Studies show daily consumption of high-flavanol chocolate improves photoprotection (about half an SPF factor of protection). Antioxidant capacity is high.', emoji: '🍫', rating: 3 },
];

function buildAntiInflammatory(Colors: ReturnType<typeof shimColors>) {
  return [
    { category: 'Reduce', foods: ['Sugar — glycates collagen, drives sebum production', 'Vegetable oils (soybean, canola, corn) — high omega-6 drives inflammation', 'Refined carbohydrates — spike insulin → androgen → sebum → acne', 'Alcohol — diuretic, inflammatory, depletes zinc', 'Dairy (for acne-prone) — IGF-1 and whey stimulate sebaceous glands'], color: Colors.red, icon: '↓' },
    { category: 'Increase', foods: ['Fatty fish 3× weekly — EPA reduces prostaglandin E2 (inflammatory)', 'Turmeric + black pepper — curcumin reduces NF-κB inflammatory pathway', 'Green tea — EGCG reduces sebum production and UV-induced inflammation', 'Berries — anthocyanins reduce oxidative stress in skin', 'Cruciferous vegetables — sulforaphane activates Nrf2 antioxidant response'], color: Colors.green, icon: '↑' },
    { category: 'Balance', foods: ['Omega-6:Omega-3 ratio — aim for 4:1 or lower (typical Western diet is 20:1)', 'Linoleic acid (sunflower seed, hemp) — essential for ceramide synthesis', 'Saturated fat balance — grass-fed sources preferred for better fatty acid profile', 'Iron — too little and too much both cause skin issues'], color: Colors.gold, icon: '⇌' },
  ];
}

const AVOID = [
  { food: 'High glycaemic foods', impact: 'Insulin spikes → IGF-1 increase → androgen stimulation → sebum overproduction → acne. Studies consistently show low-glycaemic diets reduce acne lesion counts significantly. Impact is strongest for comedonal and inflammatory acne.', severity: 'high', emoji: '🍞' },
  { food: 'Industrial vegetable oils', impact: 'Soybean, canola, corn, sunflower, and cottonseed oils are ultra-high in omega-6 linoleic acid. Excess omega-6 drives the arachidonic acid inflammatory cascade. The omega-6:omega-3 ratio in the typical diet has shifted from 1:1 (ancestral) to 20:1 (modern), dramatically increasing systemic inflammation that manifests in skin.', severity: 'high', emoji: '🫙' },
  { food: 'Sugar', impact: 'Advanced glycation end products (AGEs) form when sugar bonds to protein. In skin, AGEs attach to collagen and elastin, making them stiff, brittle, and yellow-brown. This is irreversible. AGE accumulation is a direct mechanism of skin aging. Collagen glycation is visible as sallowness in chronically high-sugar individuals.', severity: 'high', emoji: '🍬' },
  { food: 'Alcohol', impact: 'Diuretic → dehydration. Depletes zinc (vital for acne and wound healing). Disrupts deep sleep (SWS) → impairs growth hormone secretion → reduced overnight skin repair. Triggers rosacea flushing. Acetaldehyde (alcohol metabolite) directly damages skin DNA.', severity: 'high', emoji: '🍺' },
  { food: 'Dairy (for acne-prone)', impact: 'Milk contains IGF-1 (insulin-like growth factor 1) and whey protein, which stimulate the mTORC1/SREBP-1c pathway → increased sebum production and comedone formation. Skim milk has a higher glycaemic impact than whole milk. Not a universal trigger — tested with a 4-week elimination trial.', severity: 'moderate', emoji: '🥛' },
  { food: 'Trans fats (hydrogenated oils)', impact: 'Incorporated into cell membranes where they reduce fluidity and barrier function. Impair the enzymatic reactions needed for ceramide and prostaglandin synthesis. Generally being removed from food supplies but still found in some processed foods.', severity: 'moderate', emoji: '🍟' },
];

const TALLOW_DIET = [
  { title: 'Quality animal fats: diet vs skin', body: 'Grass-fed animal fat is both a topical occlusive ingredient AND a dietary food — the same fat. As a cooking fat it provides retinol (vitamin A), vitamin D, vitamin K2 (mk4 — the most bioavailable form), conjugated linoleic acid (CLA — anti-inflammatory), and a balanced saturated-fat profile for cellular membranes. The nutrients you apply topically are also available internally from the diet.' },
  { title: 'Vitamin K2 MK-4: the skin calcification protector', body: 'Grass-fed animal fats (especially from ruminants like cattle) are the primary dietary source of vitamin K2 MK-4. K2 MK-4 activates matrix GLA protein (MGP), which prevents calcium from depositing in soft tissues — including skin and elastin fibres. Arterial and tissue calcification is increasingly recognised as a driver of skin aging and elastin stiffening. Dietary K2 addresses this pathway directly.' },
  { title: 'CLA (conjugated linoleic acid) and skin inflammation', body: 'Grass-fed cattle produce significantly more CLA in their fat than grain-fed. CLA has demonstrated anti-inflammatory effects, particularly relevant to acne and inflammatory skin conditions. It modulates the same prostaglandin pathways targeted by fish oil omega-3s. Grass-fed animal fat consumed in the diet provides this benefit alongside topical occlusive use.' },
  { title: 'Cholesterol: essential for skin and not the enemy', body: 'Dietary cholesterol was feared for decades based on flawed research. Skin is 25% cholesterol by weight in the stratum corneum lipid matrix. Adequate dietary cholesterol (from eggs, animal fats) supports the skin\'s barrier. Very low cholesterol diets can impair barrier function and vitamin D synthesis (cholesterol is the precursor to vitamin D production in skin from UVB).' },
  { title: 'The whole-foods skin connection', body: 'Whole-food diets centered on animal organs, fats, bone broth, fermented foods, and seasonal produce provide skin nutrients in bioavailable forms: retinol from liver, omega-3 from fish and grass-fed meat, zinc from oysters and red meat, vitamin C from fresh vegetables and some organs. This nutrient profile supports skin structure and repair without supplementation. Quality animal fat as both food and a topical occlusive fits this whole-foods approach.' },
];

export default function SkinFoodsScreen() {
  const palette = useColors();
  const Colors = useMemo(() => shimColors(palette), [palette]);
  const styles = useMemo(() => makeStyles(palette), [palette]);
  const SKIN_NUTRIENTS = useMemo(() => buildSkinNutrients(Colors), [Colors]);
  const ANTI_INFLAMMATORY = useMemo(() => buildAntiInflammatory(Colors), [Colors]);
  const [activeTab, setActiveTab] = useState(0);
  const [expandedNutrient, setExpandedNutrient] = useState<number | null>(null);
  const [expandedFood, setExpandedFood] = useState<number | null>(null);
  const [expandedAvoid, setExpandedAvoid] = useState<number | null>(null);

  const headerAnim = useRef(new Animated.Value(0)).current;
  const contentAnim = useRef(new Animated.Value(0)).current;

  useEffect(() => {
    Animated.stagger(90, [
      Animated.timing(headerAnim, { toValue: 1, duration: 340, easing: Easing.out(Easing.cubic), useNativeDriver: true }),
      Animated.timing(contentAnim, { toValue: 1, duration: 420, easing: Easing.out(Easing.cubic), useNativeDriver: true }),
    ]).start();
  }, []);

  const severityColor = (s: string) => s === 'high' ? Colors.red : Colors.gold;
  const starRating = (n: number) => '★'.repeat(n) + '☆'.repeat(5 - n);

  return (
    <SafeAreaView style={styles.container}>
      <StatusBar barStyle="light-content" />
      <Animated.View style={[styles.header, { opacity: headerAnim, transform: [{ translateY: headerAnim.interpolate({ inputRange: [0, 1], outputRange: [-14, 0] }) }] }]}>
        <TouchableOpacity onPress={() => router.canGoBack() ? router.back() : router.replace('/(tabs)' as any)} style={styles.backBtn}>
          <Text style={styles.backText}>← Back</Text>
        </TouchableOpacity>
        <Text style={styles.headerTitle} numberOfLines={1}>Skin Foods</Text>
        <View style={{ width: 60 }} />
      </Animated.View>

      <View style={styles.hero}>
        <Text style={styles.heroTitle}>🥗 Foods for Skin</Text>
        <Text style={styles.heroSub}>Skin is built from what you eat. No topical product can compensate for nutritional deficiencies that impair collagen synthesis, barrier function, and inflammation regulation.</Text>
      </View>

      <ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.tabScroll} contentContainerStyle={styles.tabRow}>
        {TABS.map((t, i) => (
          <TouchableOpacity key={i} style={[styles.tab, activeTab === i && styles.tabActive]} onPress={() => setActiveTab(i)}>
            <Text style={[styles.tabText, activeTab === i && styles.tabTextActive]}>{t}</Text>
          </TouchableOpacity>
        ))}
      </ScrollView>

      <Animated.ScrollView style={[styles.scroll, { opacity: contentAnim }]} contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>

        {activeTab === 0 && (
          <View>
            {SKIN_NUTRIENTS.map((n, i) => (
              <TouchableOpacity key={i} style={[styles.card, { borderLeftColor: n.color, borderLeftWidth: 3 }]} onPress={() => setExpandedNutrient(expandedNutrient === i ? null : i)} activeOpacity={0.85}>
                <View style={styles.cardRow}>
                  <Text style={styles.cardEmoji}>{n.icon}</Text>
                  <View style={{ flex: 1 }}>
                    <Text style={[styles.cardTitle, { color: n.color }]}>{n.nutrient}</Text>
                    <Text style={styles.benefitText}>{n.skinBenefit}</Text>
                  </View>
                  <Text style={styles.expandIcon}>{expandedNutrient === i ? '▲' : '▼'}</Text>
                </View>
                {expandedNutrient === i && (
                  <View style={{ marginTop: 10 }}>
                    <Text style={styles.cardDetail}>{n.role}</Text>
                    <View style={styles.infoRow}><Text style={styles.infoLabel}>Sources</Text><Text style={styles.infoVal}>{n.sources}</Text></View>
                    <View style={[styles.defBlock, { borderColor: Colors.red + '33' }]}>
                      <Text style={styles.defLabel}>Deficiency Signs</Text>
                      <Text style={styles.defText}>{n.deficiencySign}</Text>
                    </View>
                  </View>
                )}
              </TouchableOpacity>
            ))}
          </View>
        )}

        {activeTab === 1 && (
          <View>
            <Text style={styles.sectionNote}>Ranked by skin nutrient density and clinical evidence. Stars indicate overall skin benefit (5 = exceptional).</Text>
            <View style={styles.foodImageGrid}>
              {TOP_FOODS.slice(0, 4).map((f, i) => {
                const imgUrl = getFoodImage(f.food);
                return (
                  <TouchableOpacity
                    key={i}
                    style={styles.foodImageCard}
                    onPress={() => setExpandedFood(expandedFood === i ? null : i)}
                    activeOpacity={0.85}
                  >
                    <Image source={{ uri: imgUrl }} style={styles.foodImage} resizeMode="cover" />
                    <LinearGradient colors={['transparent', 'rgba(0,0,0,0.82)']} style={StyleSheet.absoluteFill} />
                    <View style={styles.foodImageOverlay}>
                      <Text style={styles.foodImageEmoji}>{f.emoji}</Text>
                      <Text style={styles.foodImageName}>{f.food}</Text>
                      <Text style={styles.foodImageRating}>{starRating(f.rating)}</Text>
                    </View>
                  </TouchableOpacity>
                );
              })}
            </View>
            {TOP_FOODS.map((f, i) => (
              <TouchableOpacity key={i} style={styles.card} onPress={() => setExpandedFood(expandedFood === i ? null : i)} activeOpacity={0.85}>
                <View style={styles.cardRow}>
                  <Text style={styles.cardEmoji}>{f.emoji}</Text>
                  <View style={{ flex: 1 }}>
                    <Text style={styles.cardTitle}>{f.food}</Text>
                    <Text style={styles.ratingText}>{starRating(f.rating)}</Text>
                  </View>
                  <Text style={styles.expandIcon}>{expandedFood === i ? '▲' : '▼'}</Text>
                </View>
                {expandedFood === i && <Text style={styles.cardDetail}>{f.why}</Text>}
              </TouchableOpacity>
            ))}
          </View>
        )}

        {activeTab === 2 && (
          <View>
            {ANTI_INFLAMMATORY.map((c, i) => (
              <View key={i} style={[styles.antiCard, { borderLeftColor: c.color, borderLeftWidth: 3 }]}>
                <Text style={[styles.antiCategory, { color: c.color }]}>{c.icon} {c.category}</Text>
                {c.foods.map((f, j) => (
                  <Text key={j} style={styles.antiFoodItem}>• {f}</Text>
                ))}
              </View>
            ))}
          </View>
        )}

        {activeTab === 3 && (
          <View>
            {AVOID.map((a, i) => (
              <TouchableOpacity key={i} style={styles.card} onPress={() => setExpandedAvoid(expandedAvoid === i ? null : i)} activeOpacity={0.85}>
                <View style={styles.cardRow}>
                  <Text style={styles.cardEmoji}>{a.emoji}</Text>
                  <View style={{ flex: 1 }}>
                    <Text style={styles.cardTitle}>{a.food}</Text>
                    <View style={[styles.severityBadge, { backgroundColor: severityColor(a.severity) + '22', borderColor: severityColor(a.severity) + '55' }]}>
                      <Text style={[styles.severityText, { color: severityColor(a.severity) }]}>{a.severity.toUpperCase()} IMPACT</Text>
                    </View>
                  </View>
                  <Text style={styles.expandIcon}>{expandedAvoid === i ? '▲' : '▼'}</Text>
                </View>
                {expandedAvoid === i && <Text style={styles.cardDetail}>{a.impact}</Text>}
              </TouchableOpacity>
            ))}
          </View>
        )}

        {activeTab === 4 && (
          <View>
            <View style={styles.tallowHero}>
              <Text style={styles.tallowHeroTitle}>🌿 Dietary Fats as Skin Nutrition</Text>
              <Text style={styles.tallowHeroSub}>Quality animal fats are unique among skincare ingredients in being a genuinely functional food. The nutrients you apply are the same nutrients you can eat.</Text>
            </View>
            {TALLOW_DIET.map((p, i) => (
              <View key={i} style={styles.tallowCard}>
                <Text style={styles.tallowCardTitle}>{p.title}</Text>
                <Text style={styles.tallowCardBody}>{p.body}</Text>
              </View>
            ))}
          </View>
        )}

        <View style={{ height: 40 }} />
      </Animated.ScrollView>
    </SafeAreaView>
  );
}

function makeStyles(c: Palette) {
  const Colors = shimColors(c);
  return StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.bg },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingVertical: 12 },
  backBtn: { padding: 4 },
  backText: { color: Colors.primary, fontSize: 16 },
  headerTitle: { color: Colors.textPrimary, fontSize: 18, fontWeight: '700' },
  hero: { paddingHorizontal: 16, paddingBottom: 14, borderBottomWidth: 1, borderBottomColor: Colors.border },
  heroTitle: { color: Colors.textPrimary, fontSize: 20, fontWeight: '800', marginBottom: 6 },
  heroSub: { color: Colors.textSecondary, fontSize: 13, lineHeight: 20 },
  tabScroll: { maxHeight: 48, borderBottomWidth: 1, borderBottomColor: Colors.border },
  tabRow: { paddingHorizontal: 12, paddingVertical: 8, gap: 8 },
  tab: { paddingHorizontal: 14, paddingVertical: 6, borderRadius: 20, backgroundColor: Colors.card, borderWidth: 1, borderColor: Colors.border },
  tabActive: { backgroundColor: Colors.primary + '22', borderColor: Colors.primary },
  tabText: { color: Colors.textMuted, fontSize: 13, fontWeight: '600' },
  tabTextActive: { color: Colors.primary },
  scroll: { flex: 1 },
  scrollContent: { padding: 16 },
  sectionNote: { color: Colors.textMuted, fontSize: 12, lineHeight: 18, marginBottom: 12, fontStyle: 'italic' },
  foodImageGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 14 },
  foodImageCard: { width: '47%', height: 130, borderRadius: 14, overflow: 'hidden', position: 'relative' },
  foodImage: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, width: '100%', height: '100%' },
  foodImageOverlay: { position: 'absolute', bottom: 0, left: 0, right: 0, padding: 10 },
  foodImageEmoji: { fontSize: 16, marginBottom: 2 },
  foodImageName: { color: '#fff', fontSize: 12, fontWeight: '700', textShadowColor: 'rgba(0,0,0,0.6)', textShadowOffset: { width: 0, height: 1 }, textShadowRadius: 4 },
  foodImageRating: { color: Colors.gold, fontSize: 10, letterSpacing: 1, marginTop: 1 },
  card: { backgroundColor: Colors.card, borderRadius: 12, padding: 14, borderWidth: 1, borderColor: Colors.border, marginBottom: 10 },
  cardRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  cardEmoji: { fontSize: 18, marginTop: 2 },
  cardTitle: { color: Colors.textPrimary, fontSize: 14, fontWeight: '700', marginBottom: 4 },
  cardDetail: { color: Colors.textSecondary, fontSize: 13, lineHeight: 20, marginTop: 10 },
  expandIcon: { color: Colors.textMuted, fontSize: 12, marginTop: 4 },
  benefitText: { color: Colors.textMuted, fontSize: 12 },
  ratingText: { color: Colors.gold, fontSize: 12, letterSpacing: 2 },
  infoRow: { flexDirection: 'row', gap: 8, marginTop: 8 },
  infoLabel: { color: Colors.textMuted, fontSize: 12, fontWeight: '600', width: 60 },
  infoVal: { color: Colors.textSecondary, fontSize: 12, flex: 1 },
  defBlock: { marginTop: 10, borderRadius: 8, padding: 10, borderWidth: 1, backgroundColor: Colors.red + '0A' },
  defLabel: { color: Colors.red, fontSize: 11, fontWeight: '700', marginBottom: 4 },
  defText: { color: Colors.textSecondary, fontSize: 12, lineHeight: 18 },
  antiCard: { backgroundColor: Colors.card, borderRadius: 12, padding: 14, borderWidth: 1, borderColor: Colors.border, marginBottom: 12 },
  antiCategory: { fontSize: 15, fontWeight: '800', marginBottom: 10 },
  antiFoodItem: { color: Colors.textSecondary, fontSize: 13, lineHeight: 22 },
  severityBadge: { alignSelf: 'flex-start', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 6, borderWidth: 1, marginTop: 2 },
  severityText: { fontSize: 10, fontWeight: '700' },
  tallowHero: { backgroundColor: Colors.primary + '11', borderRadius: 14, padding: 14, borderWidth: 1, borderColor: Colors.primary + '44', marginBottom: 14 },
  tallowHeroTitle: { color: Colors.primary, fontSize: 16, fontWeight: '800', marginBottom: 6 },
  tallowHeroSub: { color: Colors.textSecondary, fontSize: 13, lineHeight: 20 },
  tallowCard: { backgroundColor: Colors.card, borderRadius: 12, padding: 14, borderWidth: 1, borderColor: Colors.border, marginBottom: 10 },
  tallowCardTitle: { color: Colors.gold, fontSize: 14, fontWeight: '700', marginBottom: 6 },
  tallowCardBody: { color: Colors.textSecondary, fontSize: 13, lineHeight: 20 },
  });
}
