import { useState, useMemo } from 'react';
import {
  View, Text, StyleSheet, ScrollView, TouchableOpacity,
  SafeAreaView, StatusBar,
} from 'react-native';
import { router } from 'expo-router';
import type { Palette } from '../../src/constants/colors';
import { useColors } from '../../src/state/theme';

function shimColors(c: Palette) {
  return {
    bg: c.bg, card: c.bgCard, cardAlt: c.bgElevated, border: c.border,
    primary: c.primary, gold: c.gold, textPrimary: c.textPrimary,
    textSecondary: c.textSecondary, textMuted: c.textMuted,
    green: c.scoreGood, red: c.scorePoor, blue: c.hydration, purple: c.darkCircles, teal: '#2DD4BF',
  };
}

const TABS = ['Why Antioxidants', 'Top Antioxidants', 'Free Radicals', 'Stacking', 'Lipid Antioxidants'];

const WHY_FACTS = [
  { fact: 'Free radicals are the primary driver of skin aging', detail: 'Free radicals — unstable molecules with unpaired electrons — react with and damage cellular structures including DNA, proteins, and lipids. They are generated by UV radiation, pollution, smoking, and even normal metabolic processes. The accumulation of this oxidative damage is called oxidative stress — and it is the foundational mechanism of skin aging and photoaging.', icon: '⚡' },
  { fact: 'Antioxidants neutralise free radicals by donating electrons', detail: 'An antioxidant donates an electron to a free radical, neutralising it without becoming reactive itself. This breaks the chain reaction of oxidative damage. The key distinction: antioxidants are "sacrificial" — they are consumed in the process. This is why constant replenishment (both dietary and topical) is essential.', icon: '🛡️' },
  { fact: 'UV generates millions of free radicals per second in skin', detail: 'A single dose of UV creates an enormous oxidative burden: singlet oxygen, superoxide radicals, hydroxyl radicals, and lipid peroxides. The skin\'s natural antioxidant systems (vitamin E, glutathione, superoxide dismutase) are overwhelmed within minutes of significant UV exposure. This is why topical antioxidants are especially relevant for morning use.', icon: '☀️' },
  { fact: 'Antioxidants work in networks — synergistically', detail: 'No single antioxidant operates in isolation. Vitamin C (water-phase) reduces spent vitamin E back to active form. Vitamin E (lipid-phase) regenerates reduced glutathione. CoQ10 and lipoic acid regenerate both C and E. This recycling network means the right combinations are far more effective than any single antioxidant at the same dose.', icon: '♻️' },
  { fact: 'Different antioxidants protect different compartments', detail: 'Water-soluble antioxidants (vitamin C, glutathione) work in the aqueous phase — within cells and in the dermis. Fat-soluble antioxidants (vitamin E, CoQ10, carotenoids) protect lipid membranes and the stratum corneum lipid bilayer. Comprehensive protection requires both phases to be covered simultaneously.', icon: '🗂️' },
];

function buildAntioxidants(Colors: ReturnType<typeof shimColors>) {
  return [
  {
    name: 'Vitamin C (L-Ascorbic Acid)',
    phase: 'water-soluble',
    source: 'topical + dietary',
    strength: 5,
    mechanism: 'Donates 2 electrons to neutralise superoxide, singlet oxygen, and hydroxyl radicals. Regenerates vitamin E. Inhibits melanogenesis. Stimulates collagen synthesis via prolyl hydroxylase cofactor activity.',
    bestFor: ['UV-induced free radical damage', 'Brightening', 'Collagen production', 'Synergy with vitamin E'],
    stability: 'Low (oxidises rapidly at pH>4 or with heat/light)',
    topical: '10–20% L-ascorbic acid AM before SPF. Stable derivatives (SAP, VC-IP) for sensitive skin.',
    dietary: 'Bell peppers, citrus, kiwi, guava, broccoli',
    color: Colors.gold,
    icon: '🍊',
  },
  {
    name: 'Vitamin E (Tocopherols)',
    phase: 'fat-soluble',
    source: 'topical + dietary',
    strength: 5,
    mechanism: 'Primary lipid-phase antioxidant. Breaks lipid peroxidation chain reactions in membrane phospholipids and stratum corneum lipids. Regenerated by vitamin C — synergy is multiplicative. Found in highest concentration in skin (actively transported there).',
    bestFor: ['Membrane protection', 'Barrier antioxidant defence', 'Synergy with C and ferulic', 'Wound healing'],
    stability: 'High when formulated correctly',
    topical: '0.5–1% tocopherol, ideally in C+E+ferulic formulations. Also present in many plant and animal lipids.',
    dietary: 'Sunflower seeds, almonds, hazelnuts, avocado, grass-fed animal fats',
    color: Colors.green,
    icon: '🌻',
  },
  {
    name: 'Ferulic Acid',
    phase: 'both',
    source: 'topical',
    strength: 4,
    mechanism: 'Plant phenolic antioxidant that doubles the stability and efficacy of vitamins C and E in combination. Provides photoprotection via UV absorption. The classic SkinCeuticals CE+Ferulic formulation (which spawned an entire product category) is built on this synergy.',
    bestFor: ['Stabilising vitamin C formulations', 'Enhancing C+E effectiveness by 4-8×', 'Photoprotection'],
    stability: 'High, also stabilises other antioxidants',
    topical: 'Typically 0.5% in C+E+ferulic serums. Enhances others — rarely used alone.',
    dietary: 'Whole grains, bran, apples, oranges, artichokes',
    color: Colors.teal,
    icon: '🌾',
  },
  {
    name: 'Niacinamide (B3 as NAD+ precursor)',
    phase: 'water-soluble',
    source: 'topical + dietary',
    strength: 4,
    mechanism: 'Converts to NAD+ intracellularly — coenzyme for 500+ reactions. Upregulates NADPH-dependent antioxidant enzymes (glutathione reductase). Activates PARP-1 (DNA repair enzyme after oxidative damage). Indirect but broad antioxidant mechanism.',
    bestFor: ['DNA repair post-UV', 'Reducing oxidative stress markers', 'Synergy with retinoids'],
    stability: 'Very high — most stable skincare active',
    topical: '2–10% AM and/or PM. All-around compatible.',
    dietary: 'Meat, fish, legumes',
    color: Colors.blue,
    icon: '💊',
  },
  {
    name: 'Resveratrol',
    phase: 'fat-soluble',
    source: 'topical + dietary',
    strength: 4,
    mechanism: 'Activates sirtuins (SIRT1/3 — "longevity proteins") that regulate mitochondrial function and oxidative stress response. Inhibits NF-κB (master inflammatory regulator). Synergistic with vitamins C and E. Topical resveratrol shows anti-aging effect at 1% concentration in studies.',
    bestFor: ['Anti-aging', 'Mitochondrial protection', 'Anti-inflammatory', 'Sirtuin activation'],
    stability: 'Moderate — oxidises with light exposure',
    topical: '1% topical in opaque packaging. PM use preferred (photosensitive).',
    dietary: 'Grape skin, red wine (small amounts), blueberries, dark chocolate',
    color: Colors.purple,
    icon: '🍇',
  },
  {
    name: 'Astaxanthin',
    phase: 'fat-soluble',
    source: 'topical + dietary',
    strength: 5,
    mechanism: 'Carotenoid antioxidant 6,000× more potent than vitamin C by ORAC measure (though this comparison is methodologically imperfect). Uniquely spans the entire cell membrane from inner to outer leaflet — covering both lipid layers simultaneously. No other antioxidant does this. Accumulates in skin with regular oral supplementation.',
    bestFor: ['UV-induced damage', 'Lipid peroxidation', 'Anti-inflammatory', 'Photoprotection (modest SPF contribution ~2 SPF units)'],
    stability: 'High in dark packaging',
    topical: '0.1–0.5% topical. Produces orange pigment on skin at higher concentrations.',
    dietary: 'Wild salmon, krill, shrimp (astaxanthin gives them pink/orange colour). Supplement: 4–12mg daily.',
    color: Colors.primary,
    icon: '🦐',
  },
  {
    name: 'CoQ10 (Ubiquinol)',
    phase: 'fat-soluble',
    source: 'topical + dietary',
    strength: 4,
    mechanism: 'Essential mitochondrial coenzyme for ATP production. In its reduced form (ubiquinol), it is a potent antioxidant that regenerates vitamin E. Topical CoQ10 accumulates in the stratum corneum and mitochondria of skin cells. Levels decline dramatically with age (by 50% by age 40 vs age 20).',
    bestFor: ['Mitochondrial energy support', 'Anti-aging', 'Reducing oxidative damage in mature skin', 'UV protection when combined with SPF'],
    stability: 'Moderate — best in antioxidant combinations',
    topical: '0.3–1% CoQ10 or 1% Idebenone (stable synthetic form). PM preferred.',
    dietary: 'Organ meats (highest), beef, sardines, broccoli, cauliflower. Supplement 100–300mg/day.',
    color: Colors.gold,
    icon: '⚡',
  },
  {
    name: 'Glutathione',
    phase: 'water-soluble',
    source: 'topical + dietary (precursors)',
    strength: 5,
    mechanism: 'The "master antioxidant" — the most abundant antioxidant in human cells. Regenerates vitamins C and E. Central to the body\'s antioxidant defence network. Topical glutathione has poor penetration in intact form. Precursors (N-acetyl cysteine, glycine, glutamine) are more effective for raising skin glutathione via dietary route.',
    bestFor: ['Broad-spectrum free radical neutralisation', 'Brightening (reduces melanin)', 'Liver and systemic detox'],
    stability: 'Low topical penetration — precursors more effective',
    topical: 'Liposomal glutathione 2% for best penetration. Or topical NAC (precursor).',
    dietary: 'Boost production: N-acetyl cysteine supplement, sulphur-rich foods (garlic, onion, cruciferous veg), whey protein.',
    color: Colors.teal,
    icon: '🧬',
  },
  ];
}

const FREE_RADICALS = [
  { type: 'Superoxide radical (O2·⁻)', source: 'Generated during mitochondrial respiration and by UV. The "seed" free radical — triggers cascade of other radical species.', neutralised: 'Superoxide dismutase (SOD) enzyme, CoQ10, resveratrol' },
  { type: 'Hydroxyl radical (·OH)', source: 'Most reactive free radical. Formed from hydrogen peroxide via Fenton reaction (requires iron/copper). Directly damages DNA and proteins.', neutralised: 'Vitamin C (water phase), glutathione. Cannot be easily quenched — prevention more effective than neutralisation.' },
  { type: 'Singlet oxygen (¹O2)', source: 'Generated by UV absorption. Reacts with double bonds in fatty acids and DNA bases.', neutralised: 'Carotenoids (astaxanthin, beta-carotene, lycopene) are specific quenchers. Vitamin E.' },
  { type: 'Lipid peroxides', source: 'Chain reaction in membrane lipids once initiated by any radical. One oxidised fatty acid in a membrane triggers dozens more.', neutralised: 'Vitamin E — specifically breaks the lipid peroxidation chain. Also the vitamin E in lipid-rich moisturisers.' },
  { type: 'ROS from pollution (PM2.5)', source: 'Particulate matter generates Fenton-reaction radicals. Accumulates in stratum corneum. Particularly relevant in urban environments.', neutralised: 'Vitamin C, ferulic acid, niacinamide (NAD+ pathway). Physical removal via cleansing.' },
];

function buildStacking(Colors: ReturnType<typeof shimColors>) {
  return [
    { stack: 'Classic AM Stack', combo: 'Vitamin C (15%) + Vitamin E (1%) + Ferulic Acid (0.5%)', why: 'The gold standard combination. Vitamin C and E synergise (each regenerates the other). Ferulic acid doubles the stability and efficacy. Together: 8× more UV protection than C alone, comprehensive radical neutralisation. Apply before SPF.', rating: Colors.green },
    { stack: 'Budget AM Stack', combo: 'Vitamin C serum (any stable form) + SPF with vitamin E', why: 'Many SPF products contain tocopherol (vitamin E). A separate vitamin C serum + tocopherol-containing SPF achieves meaningful C+E synergy without a premium formulation.', rating: Colors.teal },
    { stack: 'Sensitive Skin AM Stack', combo: 'Niacinamide 5% + Stable vitamin C derivative (ascorbyl glucoside) + SPF', why: 'Avoids irritating LAA. Niacinamide handles the NAD+/DNA repair pathway. Stable C derivative contributes antioxidant protection. Gentler but still comprehensive.', rating: Colors.blue },
    { stack: 'PM Anti-aging Stack', combo: 'Retinol + Resveratrol + Vitamin E occlusive', why: 'Retinol increases collagen. Resveratrol activates sirtuins (longevity proteins) and is PM-appropriate (photosensitive). A vitamin-E-rich occlusive completes the C+E network (if vitamin C was applied AM). Comprehensive overnight anti-aging antioxidant coverage.', rating: Colors.gold },
    { stack: 'Dietary Antioxidant Foundation', combo: 'Astaxanthin supplement 4–8mg + Vitamin C food sources + Omega-3 fish oil', why: 'Oral astaxanthin accumulates in skin over 8 weeks, providing 24-hour antioxidant protection from inside. Fish oil omega-3 reduces the inflammatory free radical cascade. This is the dietary layer that supports topical work.', rating: Colors.primary },
  ];
}

const OCCLUSIVE_BALM_AO = [
  { title: 'Vitamin E: the lipid-phase antioxidant', body: 'Lipid-rich occlusives can carry tocopherols (vitamin E) — the primary lipid-phase antioxidant in the stratum corneum. Applying a vitamin-E-containing occlusive PM replenishes the vitamin E reserves that UV, pollution, and normal metabolic oxidation depleted during the day. This overnight replenishment restores the stratum corneum\'s antioxidant capacity before the next day.' },
  { title: 'Vitamin A as anti-oxidative-stress signalling molecule', body: 'Vitamin A (retinyl esters, present in some lipid occlusives) indirectly reduces oxidative stress by activating Nrf2 — the transcription factor that upregulates the body\'s own antioxidant enzymes (superoxide dismutase, catalase, glutathione peroxidase). This boosts the skin\'s endogenous antioxidant defences rather than donating antioxidants directly.' },
  { title: 'CLA (conjugated linoleic acid) — anti-inflammatory antioxidant', body: 'Some animal-fat occlusives contain CLA, which has antioxidant and anti-inflammatory properties via Nrf2 activation and NF-κB suppression, and reduces lipid peroxidation in cell membranes. Pasture-raised sources contain notably more CLA than grain-fed.' },
  { title: 'An occlusive does not replace vitamin C as the AM antioxidant', body: 'Vitamin C\'s role is daytime: active defence against UV-generated radicals during sun exposure. A lipid occlusive\'s role is nighttime: replenishing lipid-phase antioxidants (vitamin E), supporting the barrier, and providing pro-antioxidant signalling (vitamin A via Nrf2). Different time windows and phases — complementary, not competing.' },
  { title: 'Minimal oxidation risk from saturated occlusives', body: 'A concern sometimes raised: could applied oils go rancid on skin and generate free radicals? Highly saturated occlusives resist oxidation (saturated fats are inherently more stable than polyunsaturated), and their vitamin E content self-protects. This is one reason more-saturated occlusives are preferable to highly polyunsaturated oils (like rosehip) for those concerned about oxidative damage.' },
];

export default function AntioxidantsScreen() {
  const palette = useColors();
  const Colors = useMemo(() => shimColors(palette), [palette]);
  const styles = useMemo(() => makeStyles(palette), [palette]);
  const ANTIOXIDANTS = useMemo(() => buildAntioxidants(Colors), [Colors]);
  const STACKING = useMemo(() => buildStacking(Colors), [Colors]);
  const [activeTab, setActiveTab] = useState(0);
  const [expandedFact, setExpandedFact] = useState<number | null>(null);
  const [expandedAO, setExpandedAO] = useState<number | null>(null);
  const [expandedFR, setExpandedFR] = useState<number | null>(null);
  const [expandedStack, setExpandedStack] = useState<number | null>(null);

  const strengthDots = (n: number) => '●'.repeat(n) + '○'.repeat(5 - n);

  return (
    <SafeAreaView style={styles.container}>
      <StatusBar barStyle="light-content" />
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.canGoBack() ? router.back() : router.replace('/(tabs)' as any)} style={styles.backBtn}>
          <Text style={styles.backText}>← Back</Text>
        </TouchableOpacity>
        <Text style={styles.headerTitle} numberOfLines={1}>Antioxidant Guide</Text>
        <View style={{ width: 60 }} />
      </View>

      <View style={styles.hero}>
        <Text style={styles.heroTitle}>🛡️ Antioxidants for Skin</Text>
        <Text style={styles.heroSub}>Free radical oxidation causes ~80% of visible skin aging. Antioxidants are the primary defence — but which ones to use, how to combine them, and when to apply them is rarely explained correctly.</Text>
      </View>

      <ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.tabScroll} contentContainerStyle={styles.tabRow}>
        {TABS.map((t, i) => (
          <TouchableOpacity key={i} style={[styles.tab, activeTab === i && styles.tabActive]} onPress={() => setActiveTab(i)}>
            <Text style={[styles.tabText, activeTab === i && styles.tabTextActive]}>{t}</Text>
          </TouchableOpacity>
        ))}
      </ScrollView>

      <ScrollView style={styles.scroll} contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>

        {activeTab === 0 && (
          <View>
            {WHY_FACTS.map((f, i) => (
              <TouchableOpacity key={i} style={styles.card} onPress={() => setExpandedFact(expandedFact === i ? null : i)} activeOpacity={0.85}>
                <View style={styles.cardRow}>
                  <Text style={styles.cardEmoji}>{f.icon}</Text>
                  <Text style={[styles.cardTitle, { flex: 1 }]}>{f.fact}</Text>
                  <Text style={styles.expandIcon}>{expandedFact === i ? '▲' : '▼'}</Text>
                </View>
                {expandedFact === i && <Text style={styles.cardDetail}>{f.detail}</Text>}
              </TouchableOpacity>
            ))}
          </View>
        )}

        {activeTab === 1 && (
          <View>
            {ANTIOXIDANTS.map((a, i) => (
              <TouchableOpacity key={i} style={[styles.card, { borderLeftColor: a.color, borderLeftWidth: 3 }]} onPress={() => setExpandedAO(expandedAO === i ? null : i)} activeOpacity={0.85}>
                <View style={styles.cardRow}>
                  <Text style={styles.cardEmoji}>{a.icon}</Text>
                  <View style={{ flex: 1 }}>
                    <Text style={[styles.cardTitle, { color: a.color }]}>{a.name}</Text>
                    <Text style={styles.strengthText}>{strengthDots(a.strength)} · {a.phase}</Text>
                  </View>
                  <Text style={styles.expandIcon}>{expandedAO === i ? '▲' : '▼'}</Text>
                </View>
                {expandedAO === i && (
                  <View style={{ marginTop: 10 }}>
                    <Text style={styles.cardDetail}>{a.mechanism}</Text>
                    <View style={styles.infoRow}><Text style={styles.infoLabel}>Topical</Text><Text style={styles.infoVal}>{a.topical}</Text></View>
                    <View style={styles.infoRow}><Text style={styles.infoLabel}>Dietary</Text><Text style={styles.infoVal}>{a.dietary}</Text></View>
                    <View style={styles.infoRow}><Text style={styles.infoLabel}>Stability</Text><Text style={styles.infoVal}>{a.stability}</Text></View>
                  </View>
                )}
              </TouchableOpacity>
            ))}
          </View>
        )}

        {activeTab === 2 && (
          <View>
            <Text style={styles.sectionNote}>Understanding what creates each type of free radical helps you target protection where it is most needed.</Text>
            {FREE_RADICALS.map((f, i) => (
              <TouchableOpacity key={i} style={styles.card} onPress={() => setExpandedFR(expandedFR === i ? null : i)} activeOpacity={0.85}>
                <Text style={[styles.cardTitle, { color: Colors.red }]}>{f.type}</Text>
                {expandedFR === i && (
                  <View style={{ marginTop: 8 }}>
                    <View style={styles.frRow}><Text style={styles.frLabel}>Source</Text><Text style={styles.frText}>{f.source}</Text></View>
                    <View style={styles.frRow}><Text style={styles.frLabel}>Neutralised by</Text><Text style={[styles.frText, { color: Colors.green }]}>{f.neutralised}</Text></View>
                  </View>
                )}
                {expandedFR !== i && <Text style={styles.tapHint}>Tap to see source and neutraliser ▼</Text>}
              </TouchableOpacity>
            ))}
          </View>
        )}

        {activeTab === 3 && (
          <View>
            {STACKING.map((s, i) => (
              <TouchableOpacity key={i} style={[styles.card, { borderLeftColor: s.rating, borderLeftWidth: 3 }]} onPress={() => setExpandedStack(expandedStack === i ? null : i)} activeOpacity={0.85}>
                <View>
                  <Text style={[styles.cardTitle, { color: s.rating }]}>{s.stack}</Text>
                  <Text style={styles.comboText}>{s.combo}</Text>
                </View>
                {expandedStack === i && <Text style={[styles.cardDetail, { marginTop: 10 }]}>{s.why}</Text>}
                {expandedStack !== i && <Text style={styles.tapHint}>Tap to see rationale ▼</Text>}
              </TouchableOpacity>
            ))}
          </View>
        )}

        {activeTab === 4 && (
          <View>
            <View style={styles.barrierHero}>
              <Text style={styles.barrierHeroTitle}>🌿 Lipid-Phase Antioxidants</Text>
              <Text style={styles.barrierHeroSub}>Lipid-rich occlusives contribute several antioxidant mechanisms — primarily vitamin E, vitamin A/Nrf2 signalling, and CLA. They fill the PM antioxidant role that vitamin C fills in the morning.</Text>
            </View>
            {OCCLUSIVE_BALM_AO.map((p, i) => (
              <View key={i} style={styles.barrierCard}>
                <Text style={styles.barrierCardTitle}>{p.title}</Text>
                <Text style={styles.barrierCardBody}>{p.body}</Text>
              </View>
            ))}
          </View>
        )}

        <View style={{ height: 40 }} />
      </ScrollView>
    </SafeAreaView>
  );
}

function makeStyles(c: Palette) {
  const Colors = shimColors(c);
  return StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.bg },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingVertical: 12 },
  backBtn: { padding: 4 },
  backText: { color: Colors.primary, fontSize: 16 },
  headerTitle: { color: Colors.textPrimary, fontSize: 18, fontWeight: '700' },
  hero: { paddingHorizontal: 16, paddingBottom: 14, borderBottomWidth: 1, borderBottomColor: Colors.border },
  heroTitle: { color: Colors.textPrimary, fontSize: 20, fontWeight: '800', marginBottom: 6 },
  heroSub: { color: Colors.textSecondary, fontSize: 13, lineHeight: 20 },
  tabScroll: { maxHeight: 48, borderBottomWidth: 1, borderBottomColor: Colors.border },
  tabRow: { paddingHorizontal: 12, paddingVertical: 8, gap: 8 },
  tab: { paddingHorizontal: 14, paddingVertical: 6, borderRadius: 20, backgroundColor: Colors.card, borderWidth: 1, borderColor: Colors.border },
  tabActive: { backgroundColor: Colors.primary + '22', borderColor: Colors.primary },
  tabText: { color: Colors.textMuted, fontSize: 13, fontWeight: '600' },
  tabTextActive: { color: Colors.primary },
  scroll: { flex: 1 },
  scrollContent: { padding: 16 },
  sectionNote: { color: Colors.textMuted, fontSize: 12, lineHeight: 18, marginBottom: 12, fontStyle: 'italic' },
  card: { backgroundColor: Colors.card, borderRadius: 12, padding: 14, borderWidth: 1, borderColor: Colors.border, marginBottom: 10 },
  cardRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  cardEmoji: { fontSize: 18, marginTop: 2 },
  cardTitle: { color: Colors.textPrimary, fontSize: 14, fontWeight: '700', marginBottom: 4 },
  cardDetail: { color: Colors.textSecondary, fontSize: 13, lineHeight: 20 },
  expandIcon: { color: Colors.textMuted, fontSize: 12, marginTop: 4 },
  strengthText: { color: Colors.gold, fontSize: 11, letterSpacing: 2 },
  infoRow: { flexDirection: 'row', gap: 8, marginTop: 8 },
  infoLabel: { color: Colors.textMuted, fontSize: 12, fontWeight: '600', width: 65 },
  infoVal: { color: Colors.textSecondary, fontSize: 12, flex: 1 },
  frRow: { flexDirection: 'row', gap: 8, marginBottom: 6 },
  frLabel: { color: Colors.textMuted, fontSize: 12, fontWeight: '600', width: 90 },
  frText: { color: Colors.textSecondary, fontSize: 12, flex: 1 },
  tapHint: { color: Colors.textMuted, fontSize: 11, marginTop: 4 },
  comboText: { color: Colors.textSecondary, fontSize: 12, fontStyle: 'italic' },
  barrierHero: { backgroundColor: Colors.primary + '11', borderRadius: 14, padding: 14, borderWidth: 1, borderColor: Colors.primary + '44', marginBottom: 14 },
  barrierHeroTitle: { color: Colors.primary, fontSize: 16, fontWeight: '800', marginBottom: 6 },
  barrierHeroSub: { color: Colors.textSecondary, fontSize: 13, lineHeight: 20 },
  barrierCard: { backgroundColor: Colors.card, borderRadius: 12, padding: 14, borderWidth: 1, borderColor: Colors.border, marginBottom: 10 },
  barrierCardTitle: { color: Colors.gold, fontSize: 14, fontWeight: '700', marginBottom: 6 },
  barrierCardBody: { color: Colors.textSecondary, fontSize: 13, lineHeight: 20 },
  });
}
